#!/usr/bin/env python3
"""Project verifier for land-work's project-verifier gate.

Generated by bento's `wire-land-verifier` skill. Runs this repo's confirmed
gate command(s) and emits the schema_version:1 result that
`land-work-run-verifier.py` expects as its final stdout line, timing each
check (`wall_seconds`) and, for a go-task command, detecting whether it was
served from cache (`executed`) from go-task v3.x's unlocalised
`Task "<name>" is up to date` skip message -- catches the case where a
"passed" result ran zero real tests because every task's checksummed sources
were unchanged (bento-rdtn.6).

Edit CHECKS when the repo's real gate changes. Keep the trailing JSON line as
the only thing this script writes to stdout.
"""
from __future__ import annotations

import json
import re
import subprocess
import sys
import time
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]

# (name, argv, is_go_task) -- is_go_task enables the cache-skip detection
# below; only checks whose argv invokes the `task` CLI get it.
CHECKS: list[tuple[str, list[str], bool]] = [
    ("syntax-check", ["ansible-playbook", "--syntax-check", "playbook.yml"], False),
]


def _go_task_target_names(cmd: list[str]) -> list[str]:
    """Requested go-task target names from its argv (everything after the
    `task` binary itself that isn't a flag). A bare `task` with no targets
    runs the "default" task, which go-task's own skip message names
    "default"."""
    names = [arg for arg in cmd[1:] if not arg.startswith("-")]
    return names or ["default"]


def main() -> int:
    selected_checks = []
    overall = "passed"
    for name, cmd, is_go_task in CHECKS:
        print(f"==> {name}", file=sys.stderr)
        start = time.monotonic()
        if is_go_task:
            # Captured (not streamed straight to stderr) so the cache-skip
            # message can be scanned for; echoed to stderr afterward so
            # nothing is lost from the log.
            result = subprocess.run(cmd, cwd=REPO_ROOT, capture_output=True, text=True)
            sys.stderr.write(result.stdout)
            sys.stderr.write(result.stderr)
            combined = result.stdout + result.stderr
            # A single invocation can run multiple targets (`task lint test
            # build`); only call the whole check cached if EVERY requested
            # target reports the skip message for its own name, not merely
            # if any one of them does.
            executed = not all(
                re.search(rf'Task "{re.escape(target)}" is up to date', combined)
                for target in _go_task_target_names(cmd)
            )
        else:
            result = subprocess.run(cmd, cwd=REPO_ROOT, stdout=sys.stderr, stderr=sys.stderr)
            executed = None
        wall_seconds = round(time.monotonic() - start, 3)
        status = "passed" if result.returncode == 0 else "failed"
        if status == "failed":
            overall = "failed"
        check_entry = {"name": name, "status": status, "wall_seconds": wall_seconds}
        if executed is not None:
            check_entry["executed"] = executed
        selected_checks.append(check_entry)
    print(json.dumps({
        "schema_version": 1,
        "status": overall,
        "selected_checks": selected_checks,
    }))
    return 0 if overall == "passed" else 1


if __name__ == "__main__":
    raise SystemExit(main())
